apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: url-shortener
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          env:
            - name: CLICKHOUSE_DB
              value: analytics
            - name: CLICKHOUSE_USER
              value: chuser
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key:  CLICKHOUSE_PASSWORD
          resources:
            requests:
              cpu:    "1000m"
              memory: "2Gi"
            limits:
              cpu:    "4000m"
              memory: "8Gi"
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: url-shortener
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
    - name: native
      port: 9000